// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaXBGEkH1_FYAO35JJ8Taymm9OYn8i6a8',
    appId: '1:385319418573:web:a2602090d1fb757fffc784',
    messagingSenderId: '385319418573',
    projectId: 'flutter-firebase-examp1',
    authDomain: 'flutter-firebase-examp1.firebaseapp.com',
    storageBucket: 'flutter-firebase-examp1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEliQ0s5_EHmlnFPpPT_TGTBJBJEnJe_U',
    appId: '1:385319418573:android:5d900025e2a15ac4ffc784',
    messagingSenderId: '385319418573',
    projectId: 'flutter-firebase-examp1',
    storageBucket: 'flutter-firebase-examp1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFrGLcXPNNQxz97abjPxljjU5LA8-u93w',
    appId: '1:385319418573:ios:00c50648555e75d4ffc784',
    messagingSenderId: '385319418573',
    projectId: 'flutter-firebase-examp1',
    storageBucket: 'flutter-firebase-examp1.appspot.com',
    iosClientId: '385319418573-t69oojnjcs0ju8rfj2feor7rmvd8hun8.apps.googleusercontent.com',
    iosBundleId: 'com.safauludogan.flutterFirebaseApp1',
  );
}
